let c= prompt ("nhập số")
let d= prompt ("nhập số")
let g= prompt ("nhập số")
let h= prompt ("nhập số")
let b= prompt ("nhập số")
console.log ("tích",c*d*h*b*g)
console.log ("tổng",c+g+d+g+h)
console.log ("số bé nhất")
console.log("số oén nhất")